DOP-2055: Add IA support
mongodb/snooty-parser pull request #299
Opened 2021-03-30 20:22 UTC by sophstad

- Add support for `ia` and `entry` directives
  - Save their contents to page-level options, as well as to a sitewide `iatree` entry in the `metadata` document
  - If `iatree` exists, use it to generate breadcrumbs and in-order traversal of site (i.e. have it replace `toctree`)
- Add new new testing util, `check_toctree_testing_string()`, which uses an approach similar to `check_ast_testing_string()` to enable tests that are more legible than a direct dict comparison
  - Convert existing tests to use function

2021-03-31 19:37 UTC, sophstad commented on snooty/postprocess.py
> +                url = entry.options.get("url")
I don't think we can enforce this, sadly. `:url:` could definitely point at non-MongoDB or non-docs links (or even a docs link that would be invalid with a trailing slash, like https://docs.mongodb.com/realm-sdks/dotnet/10.0.0-beta.1/reference/Realms.Realm.html).

2021-03-31 19:37 UTC, sophstad commented on snooty/postprocess.py
> +                slug = entry.options.get("url")
Great point, I'll add some diagnostics/validation around this case.

2021-04-05 14:14 UTC, i80and requested changes
A couple of thoughts!

2021-04-05 14:14 UTC, i80and commented on snooty/postprocess.py
> +                        "IA entry directives with snooty-name option must include url",
`must include the :url: option` might make this more clear

2021-04-05 14:14 UTC, i80and commented on snooty/postprocess.py
> +        fileid_with_ext = self.slug_fileid_mapping[relative.as_posix()]
Is there a possible scenario where this would throw KeyError?

2021-04-05 15:13 UTC, sophstad commented on snooty/postprocess.py
> +        if not isinstance(node, n.Directive) or not node.name == "ia":
The domain on this directive looks to be an empty string, still appropriate to match you think?

2021-04-05 15:15 UTC, i80and commented on snooty/postprocess.py
> +        if not isinstance(node, n.Directive) or not node.name == "ia":
Yep -- I think we *should* put things in domains, in general, but an empty string is still part of the canonical identifier

2021-04-19 03:50 UTC, i80and requested changes
Just some style nits, then I'll lgtm!

2021-04-19 03:50 UTC, i80and commented on snooty/diagnostics.py
> +class InvalidToctree(Diagnostic, MakeCorrectionMixin):
This should be `InvalidTocTree` for consistency

2021-04-19 03:50 UTC, i80and commented on snooty/postprocess.py
> +        if not starting_page.ast.options.get("ia"):
`"ia" not in starting_page.ast.options` might make the intent a little more clear

2021-04-19 03:50 UTC, i80and commented on snooty/postprocess.py
> +    def iterate_ia(self, page: Page, result: Dict[str, SerializableType]) -> None:
Could we have a docstring to briefly explain the purpose and behavior of this method?

2021-04-19 03:50 UTC, i80and commented on snooty/postprocess.py
>          """Generate breadcrumbs for each page represented in the toctree"""
Should this docstring be updated to `in the provided toctree`?

2021-04-19 17:55 UTC, i80and approved these changes
🤘🏻

2021-04-19 19:40 UTC, merged