(DOP-2320) Add tocicon page-level option to toctree_node
mongodb/snooty-parser pull request #367
Opened 2021-12-20 21:04 UTC by gjchong25

2022-01-04 15:34 UTC, i80and requested changes

2022-01-04 15:34 UTC, i80and commented on snooty/postprocess.py
> +                    isSyncPillOn = False
Python convention is snake_case

2022-01-04 15:34 UTC, i80and commented on snooty/postprocess.py
> +                            "tocicon": isSyncPillOn,
this should really be a string, not a boolean. see above

2022-01-04 15:34 UTC, i80and commented on snooty/postprocess.py
> +                            if (
I'd say we should just pass in the string, rather than checking it against "sync"

2022-01-04 15:34 UTC, i80and commented on snooty/test_postprocess.py
> +    <toctree slug="page1" drawer="True" tocicon="False" />
If there's no tocicon set, we shouldn't have this entry in the options I think. Additionally, we should have a test *with* a tocicon. lmk if you need help with that!

2022-01-04 20:56 UTC, i80and approved these changes

2022-01-05 15:00 UTC, rayangler approved these changes

2022-01-06 14:32 UTC, merged